<?php

namespace Codeception\Module;


use tad\WPBrowser\Utils\PathUtils;

class EmbeddedWPLoader extends WPLoader
{
    protected function getWpRootFolder()
    {
        codecept_root_dir('');
    }


    protected function defineGlobals()
    {
        parent::defineGlobals(); // TODO: Change the autogenerated stub
    }

}